# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20170324_1359'),
        ('blackbeltapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_on_trip', to='login_app.Users'),
            preserve_default=False,
        ),
    ]
