# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
